% Function localRecompile_plasma_nn_wrapper_wrapper_fixpt_fil recreates a MEX-function plasma_nn_wrapper_wrapper_fixpt_fil_mex from MATLAB function plasma_nn_wrapper_wrapper_fixpt_fil
% Generated by MATLAB 9.10 and HDL Coder 3.18
function localRecompile_plasma_nn_wrapper_wrapper_fixpt_fil

load('/home/kimberlychan/Desktop/DNN_Generality/matlab/codegen0_H5_L2_wL13_UnrollLoops/codegen/plasma_nn_wrapper/fil/localCodegenArgs_plasma_nn_wrapper_wrapper_fixpt_fil');

fxptPath = '/home/kimberlychan/Desktop/DNN_Generality/matlab/codegen0_H5_L2_wL13_UnrollLoops/codegen/plasma_nn_wrapper/fixpt';
addpath(fxptPath);
cleanupObj = onCleanup(@() rmpath(fxptPath));
codegen -args exInputs -o '/home/kimberlychan/Desktop/DNN_Generality/matlab/codegen0_H5_L2_wL13_UnrollLoops/codegen/plasma_nn_wrapper/fil/plasma_nn_wrapper_wrapper_fixpt_fil_mex' plasma_nn_wrapper_wrapper_fixpt_fil;

