/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mpc_implicit(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mpc_implicit_alloc_mem(void);
int mpc_implicit_init_mem(int mem);
void mpc_implicit_free_mem(int mem);
int mpc_implicit_checkout(void);
void mpc_implicit_release(int mem);
void mpc_implicit_incref(void);
void mpc_implicit_decref(void);
casadi_int mpc_implicit_n_out(void);
casadi_int mpc_implicit_n_in(void);
casadi_real mpc_implicit_default_in(casadi_int i);
const char* mpc_implicit_name_in(casadi_int i);
const char* mpc_implicit_name_out(casadi_int i);
const casadi_int* mpc_implicit_sparsity_in(casadi_int i);
const casadi_int* mpc_implicit_sparsity_out(casadi_int i);
int mpc_implicit_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
