// -------------------------------------------------------------
// 
// File Name: /home/kimberlychan/Desktop/DNN_Generality/matlab/codegen0_H5_L3_wL20_LoopNone/codegen/plasma_nn_wrapper/hdlsrc/plasma_nn_wrapper_fixpt.v
// Created: 2022-07-22 13:19:10
// 
// Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: plasma_nn_wrapper_fixpt
// Source Path: plasma_nn_wrapper_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module plasma_nn_wrapper_fixpt
          (x1_1,
           x1_2,
           x1_3,
           y1_1,
           y1_2);


  input   signed [19:0] x1_1;  // sfix20_En18
  input   signed [19:0] x1_2;  // sfix20_En18
  input   signed [2:0] x1_3;  // sfix3
  output  signed [19:0] y1_1;  // sfix20_En18
  output  signed [19:0] y1_2;  // sfix20_En18


  reg signed [19:0] y1_1_1;  // sfix20_En18
  reg signed [19:0] y1_2_1;  // sfix20_En18
  reg signed [19:0] plasma_nn_wrapper_fixpt_x1 [0:2];  // sfix20_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c [0:2];  // sfix21_En18 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y [0:2];  // sfix20_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_0 [0:2];  // sfix21_En18 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y_0 [0:2];  // sfix20_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_1 [0:2];  // sfix21_En18 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_xp1 [0:2];  // sfix20_En18 [3]
  reg signed [41:0] plasma_nn_wrapper_fixpt_c_2 [0:4];  // sfix42_En36 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_3 [0:4];  // sfix43_En36 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_maxval [0:4];  // sfix43_En36 [5]
  reg [19:0] plasma_nn_wrapper_fixpt_a1 [0:4];  // ufix20_En19 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_4 [0:4];  // sfix43_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_c_5 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_maxval_0 [0:4];  // sfix44_En38 [5]
  reg [19:0] plasma_nn_wrapper_fixpt_a2 [0:4];  // ufix20_En20 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_6 [0:4];  // sfix43_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_c_7 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_maxval_1 [0:4];  // sfix44_En38 [5]
  reg [19:0] plasma_nn_wrapper_fixpt_a3 [0:4];  // ufix20_En21 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_8 [0:1];  // sfix43_En39 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a4 [0:1];  // sfix20_En20 [2]
  reg signed [22:0] plasma_nn_wrapper_fixpt_c_9 [0:1];  // sfix23_En20 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a [0:1];  // sfix20_En18 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_x [0:1];  // sfix20_En18 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_10 [0:1];  // sfix21_En18 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y1 [0:1];  // sfix20_En20 [2]
  reg signed [31:0] plasma_nn_wrapper_fixpt_k;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_0;  // int32
  reg signed [42:0] plasma_nn_wrapper_fixpt_tmp;  // sfix43_En36
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_1;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l;  // int32
  reg signed [43:0] plasma_nn_wrapper_fixpt_tmp_0;  // sfix44_En38
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_2;  // int32
  reg signed [43:0] plasma_nn_wrapper_fixpt_tmp_1;  // sfix44_En38
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_3;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_0;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_1;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_2;  // int32
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0 [0:14];  // sfix20_En18 [15]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_0 [0:24];  // sfix20_En19 [25]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_1 [0:24];  // sfix20_En18 [25]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_2 [0:9];  // sfix20_En18 [10]
  reg signed [42:0] plasma_nn_wrapper_fixpt_t_0 [0:4];  // sfix43_En36 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_1 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_2 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_3 [0:1];  // sfix44_En39 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_sub_cast [0:2];  // sfix21_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_add_cast [0:2];  // sfix21_En18 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_0 [0:4];  // sfix43_En36 [5]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_1 [0:2];  // sfix43_En36 [3]
  reg signed [39:0] plasma_nn_wrapper_fixpt_mul_temp [0:2];  // sfix40_En36 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_2 [0:2];  // sfix43_En36 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_temp [0:2];  // sfix43_En36 [3]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_3 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_4 [0:4];  // sfix44_En38 [5]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast [0:4];  // sfix21_En19 [5]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_0 [0:4];  // sfix41_En38 [5]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_5 [0:4];  // sfix40_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_6 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_0 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_7 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_8 [0:4];  // sfix44_En38 [5]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast_0 [0:4];  // sfix21_En20 [5]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_1 [0:4];  // sfix41_En38 [5]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_9 [0:4];  // sfix40_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_10 [0:4];  // sfix44_En38 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_1 [0:4];  // sfix44_En38 [5]
  reg [19:0] plasma_nn_wrapper_fixpt_cast_1 [0:4];  // ufix20_En19 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_11 [0:1];  // sfix44_En39 [2]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_2 [0:1];  // sfix44_En39 [2]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_12 [0:4];  // sfix44_En39 [5]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_13 [0:4];  // sfix64 [5]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast_2 [0:4];  // sfix21_En21 [5]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_2 [0:4];  // sfix41_En39 [5]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_14 [0:4];  // sfix40_En39 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_15 [0:4];  // sfix44_En39 [5]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_3 [0:4];  // sfix44_En39 [5]
  reg [19:0] plasma_nn_wrapper_fixpt_cast_3 [0:4];  // ufix20_En19 [5]
  reg signed [22:0] plasma_nn_wrapper_fixpt_sub_cast_0 [0:1];  // sfix23_En20 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_add_cast_16 [0:1];  // sfix21_En18 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_cast_4 [0:1];  // sfix20_En18 [2]
  reg signed [31:0] plasma_nn_wrapper_fixpt_cast_5;  // int32
  reg signed [63:0] plasma_nn_wrapper_fixpt_mul_temp_3;  // sfix64
  reg signed [31:0] plasma_nn_wrapper_fixpt_cast_6;  // int32
  reg signed [63:0] plasma_nn_wrapper_fixpt_mul_temp_4;  // sfix64
  reg signed [31:0] plasma_nn_wrapper_fixpt_cast_7;  // int32
  reg signed [63:0] plasma_nn_wrapper_fixpt_mul_temp_5;  // sfix64
  reg signed [33:0] plasma_nn_wrapper_fixpt_t_4 [0:4] [0:2];  // sfix34 [5x3]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_5 [0:4] [0:2];  // sfix64 [5x3]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_6 [0:4] [0:2];  // sfix64 [5x3]
  reg signed [33:0] plasma_nn_wrapper_fixpt_t_7 [0:4] [0:4];  // sfix34 [5x5]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_8 [0:4] [0:4];  // sfix64 [5x5]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_9 [0:4] [0:4];  // sfix64 [5x5]
  reg signed [33:0] plasma_nn_wrapper_fixpt_t_10 [0:4] [0:4];  // sfix34 [5x5]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_11 [0:4] [0:4];  // sfix64 [5x5]
  reg signed [63:0] plasma_nn_wrapper_fixpt_t_12 [0:4] [0:4];  // sfix64 [5x5]


  always @(x1_1, x1_2, x1_3) begin
    plasma_nn_wrapper_fixpt_a0[0] = 20'sb11111001100010101111;
    plasma_nn_wrapper_fixpt_a0[1] = 20'sb00110001110100100010;
    plasma_nn_wrapper_fixpt_a0[2] = 20'sb00010011110110100100;
    plasma_nn_wrapper_fixpt_a0[3] = 20'sb11010100110100000111;
    plasma_nn_wrapper_fixpt_a0[4] = 20'sb11001111001110110101;
    plasma_nn_wrapper_fixpt_a0[5] = 20'sb00001101000110010000;
    plasma_nn_wrapper_fixpt_a0[6] = 20'sb01000111100000100100;
    plasma_nn_wrapper_fixpt_a0[7] = 20'sb11101011100100011100;
    plasma_nn_wrapper_fixpt_a0[8] = 20'sb00001010111010100000;
    plasma_nn_wrapper_fixpt_a0[9] = 20'sb11011100101001011101;
    plasma_nn_wrapper_fixpt_a0[10] = 20'sb10101010110000100101;
    plasma_nn_wrapper_fixpt_a0[11] = 20'sb00011001000001010001;
    plasma_nn_wrapper_fixpt_a0[12] = 20'sb00000000110000110011;
    plasma_nn_wrapper_fixpt_a0[13] = 20'sb00011001011110110101;
    plasma_nn_wrapper_fixpt_a0[14] = 20'sb00110010000010010001;
    plasma_nn_wrapper_fixpt_a0_0[0] = 20'sb00110110001100101101;
    plasma_nn_wrapper_fixpt_a0_0[1] = 20'sb11000001000110001010;
    plasma_nn_wrapper_fixpt_a0_0[2] = 20'sb01101011101000010000;
    plasma_nn_wrapper_fixpt_a0_0[3] = 20'sb10111110010101111010;
    plasma_nn_wrapper_fixpt_a0_0[4] = 20'sb00011010101110111001;
    plasma_nn_wrapper_fixpt_a0_0[5] = 20'sb11111100001010111001;
    plasma_nn_wrapper_fixpt_a0_0[6] = 20'sb10110010010101000001;
    plasma_nn_wrapper_fixpt_a0_0[7] = 20'sb10101010111000101010;
    plasma_nn_wrapper_fixpt_a0_0[8] = 20'sb00011101101101010001;
    plasma_nn_wrapper_fixpt_a0_0[9] = 20'sb00000011110011000101;
    plasma_nn_wrapper_fixpt_a0_0[10] = 20'sb11011010000001100101;
    plasma_nn_wrapper_fixpt_a0_0[11] = 20'sb01010100101100010010;
    plasma_nn_wrapper_fixpt_a0_0[12] = 20'sb00010101110100111101;
    plasma_nn_wrapper_fixpt_a0_0[13] = 20'sb00001100101110101010;
    plasma_nn_wrapper_fixpt_a0_0[14] = 20'sb01101010110011010011;
    plasma_nn_wrapper_fixpt_a0_0[15] = 20'sb11001001001011001011;
    plasma_nn_wrapper_fixpt_a0_0[16] = 20'sb01000001110101111101;
    plasma_nn_wrapper_fixpt_a0_0[17] = 20'sb01000000111101000110;
    plasma_nn_wrapper_fixpt_a0_0[18] = 20'sb11100001011001001110;
    plasma_nn_wrapper_fixpt_a0_0[19] = 20'sb00010001010111001100;
    plasma_nn_wrapper_fixpt_a0_0[20] = 20'sb10010011011010110010;
    plasma_nn_wrapper_fixpt_a0_0[21] = 20'sb10001101110011111010;
    plasma_nn_wrapper_fixpt_a0_0[22] = 20'sb00000111111000100101;
    plasma_nn_wrapper_fixpt_a0_0[23] = 20'sb01000111011101111000;
    plasma_nn_wrapper_fixpt_a0_0[24] = 20'sb01101111000110110101;
    plasma_nn_wrapper_fixpt_a0_1[0] = 20'sb11011110011111000000;
    plasma_nn_wrapper_fixpt_a0_1[1] = 20'sb00100101101010110001;
    plasma_nn_wrapper_fixpt_a0_1[2] = 20'sb11100111110101011110;
    plasma_nn_wrapper_fixpt_a0_1[3] = 20'sb11111111000111011001;
    plasma_nn_wrapper_fixpt_a0_1[4] = 20'sb11011010010011000110;
    plasma_nn_wrapper_fixpt_a0_1[5] = 20'sb00001101000011011011;
    plasma_nn_wrapper_fixpt_a0_1[6] = 20'sb11100001101010010000;
    plasma_nn_wrapper_fixpt_a0_1[7] = 20'sb00010011101110001101;
    plasma_nn_wrapper_fixpt_a0_1[8] = 20'sb00011000001110000010;
    plasma_nn_wrapper_fixpt_a0_1[9] = 20'sb00011111110000110110;
    plasma_nn_wrapper_fixpt_a0_1[10] = 20'sb10101100101001101001;
    plasma_nn_wrapper_fixpt_a0_1[11] = 20'sb11001010101110101010;
    plasma_nn_wrapper_fixpt_a0_1[12] = 20'sb11011101010011110001;
    plasma_nn_wrapper_fixpt_a0_1[13] = 20'sb00100111010101110111;
    plasma_nn_wrapper_fixpt_a0_1[14] = 20'sb11010001110101111111;
    plasma_nn_wrapper_fixpt_a0_1[15] = 20'sb00101001101101000101;
    plasma_nn_wrapper_fixpt_a0_1[16] = 20'sb00000100111010000110;
    plasma_nn_wrapper_fixpt_a0_1[17] = 20'sb00111111100000010101;
    plasma_nn_wrapper_fixpt_a0_1[18] = 20'sb11001010000000011010;
    plasma_nn_wrapper_fixpt_a0_1[19] = 20'sb11111000101010011010;
    plasma_nn_wrapper_fixpt_a0_1[20] = 20'sb11000011000111011001;
    plasma_nn_wrapper_fixpt_a0_1[21] = 20'sb00111011000111110111;
    plasma_nn_wrapper_fixpt_a0_1[22] = 20'sb11000000100101111101;
    plasma_nn_wrapper_fixpt_a0_1[23] = 20'sb00011001010010000000;
    plasma_nn_wrapper_fixpt_a0_1[24] = 20'sb11110111110011100010;
    plasma_nn_wrapper_fixpt_a0_2[0] = 20'sb10111111110100100110;
    plasma_nn_wrapper_fixpt_a0_2[1] = 20'sb01010001100010111011;
    plasma_nn_wrapper_fixpt_a0_2[2] = 20'sb11010111010001101100;
    plasma_nn_wrapper_fixpt_a0_2[3] = 20'sb11100001110001000100;
    plasma_nn_wrapper_fixpt_a0_2[4] = 20'sb11010010101000010000;
    plasma_nn_wrapper_fixpt_a0_2[5] = 20'sb11010001011010101011;
    plasma_nn_wrapper_fixpt_a0_2[6] = 20'sb00100100001001000101;
    plasma_nn_wrapper_fixpt_a0_2[7] = 20'sb00000010000000111010;
    plasma_nn_wrapper_fixpt_a0_2[8] = 20'sb10111000100110001110;
    plasma_nn_wrapper_fixpt_a0_2[9] = 20'sb11000001100000001001;
    plasma_nn_wrapper_fixpt_t_0[0] = 43'sh0064D920000;
    plasma_nn_wrapper_fixpt_t_0[1] = 43'sh002A37C0000;
    plasma_nn_wrapper_fixpt_t_0[2] = 43'sh7F46F9C0000;
    plasma_nn_wrapper_fixpt_t_0[3] = 43'sh7F4C7040000;
    plasma_nn_wrapper_fixpt_t_0[4] = 43'sh7F83D800000;
    plasma_nn_wrapper_fixpt_t_1[0] = 44'shFC906200000;
    plasma_nn_wrapper_fixpt_t_1[1] = 44'sh008CF300000;
    plasma_nn_wrapper_fixpt_t_1[2] = 44'shFC62F100000;
    plasma_nn_wrapper_fixpt_t_1[3] = 44'shFC186000000;
    plasma_nn_wrapper_fixpt_t_1[4] = 44'shFF3AA300000;
    plasma_nn_wrapper_fixpt_t_2[0] = 44'sh045EA900000;
    plasma_nn_wrapper_fixpt_t_2[1] = 44'shFCACEC00000;
    plasma_nn_wrapper_fixpt_t_2[2] = 44'shFF32C100000;
    plasma_nn_wrapper_fixpt_t_2[3] = 44'shFD28F200000;
    plasma_nn_wrapper_fixpt_t_2[4] = 44'sh016DB900000;
    plasma_nn_wrapper_fixpt_t_3[0] = 44'sh05C5A900000;
    plasma_nn_wrapper_fixpt_t_3[1] = 44'shFBD1E700000;
    plasma_nn_wrapper_fixpt_tmp = 43'sh00000000000;
    plasma_nn_wrapper_fixpt_tmp_0 = 44'sh00000000000;
    plasma_nn_wrapper_fixpt_tmp_1 = 44'sh00000000000;
    plasma_nn_wrapper_fixpt_mul_temp_3 = 64'sh0000000000000000;
    plasma_nn_wrapper_fixpt_mul_temp_4 = 64'sh0000000000000000;
    plasma_nn_wrapper_fixpt_mul_temp_5 = 64'sh0000000000000000;
    plasma_nn_wrapper_fixpt_cast_5 = 32'sd0;
    plasma_nn_wrapper_fixpt_cast_6 = 32'sd0;
    plasma_nn_wrapper_fixpt_cast_7 = 32'sd0;
    //HDL code generation from MATLAB function: plasma_nn_wrapper_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    plasma_nn_wrapper_fixpt_x1[0] = x1_1;
    plasma_nn_wrapper_fixpt_x1[1] = x1_2;
    plasma_nn_wrapper_fixpt_x1[2] = {x1_3[1:0], 18'b000000000000000000};
    //PLASMA_NN neural network simulation function.
    //
    // Auto-generated by MATLAB, 22-Jul-2022 13:18:24.
    // 
    // [y1] = plasma_nn(x1) takes these arguments:
    //   x = 3xQ matrix, input #1
    // and returns:
    //   y = 2xQ matrix, output #1
    // where Q is the number of samples.
    // ===== NEURAL NETWORK CONSTANTS =====
    // Input 1
    // Layer 1
    // Layer 2
    // Layer 3
    // Layer 4
    // Output 1
    // ===== SIMULATION ========
    // Dimensions
    // samples
    // Input 1
    // ===== MODULE FUNCTIONS ========
    // Map Minimum and Maximum Input Processing Function

    for(plasma_nn_wrapper_fixpt_k = 32'sd0; plasma_nn_wrapper_fixpt_k <= 32'sd2; plasma_nn_wrapper_fixpt_k = plasma_nn_wrapper_fixpt_k + 32'sd1) begin
      plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] - 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k][19:0];
      plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k][19:0];
      plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] + 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k][19:0];
    end

    // Layer 1
    // Linear Positive Transfer Function
    // Layer 2

    for(plasma_nn_wrapper_fixpt_l_0 = 32'sd0; plasma_nn_wrapper_fixpt_l_0 <= 32'sd4; plasma_nn_wrapper_fixpt_l_0 = plasma_nn_wrapper_fixpt_l_0 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0] = 42'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_0 = 32'sd0; plasma_nn_wrapper_fixpt_k_0 <= 32'sd2; plasma_nn_wrapper_fixpt_k_0 = plasma_nn_wrapper_fixpt_k_0 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0][41], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0]};
        plasma_nn_wrapper_fixpt_cast_5 = plasma_nn_wrapper_fixpt_k_0;
        // CSD Encoding (5) : 0101; Cost (Adders) = 1
        plasma_nn_wrapper_fixpt_t_4[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0] = {plasma_nn_wrapper_fixpt_cast_5, 2'b00};
        plasma_nn_wrapper_fixpt_t_5[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0] = {{30{plasma_nn_wrapper_fixpt_t_4[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0][33]}}, plasma_nn_wrapper_fixpt_t_4[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0]};
        plasma_nn_wrapper_fixpt_t_6[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0] = {{32{plasma_nn_wrapper_fixpt_cast_5[31]}}, plasma_nn_wrapper_fixpt_cast_5};
        plasma_nn_wrapper_fixpt_mul_temp_3 = plasma_nn_wrapper_fixpt_t_5[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0] + plasma_nn_wrapper_fixpt_t_6[plasma_nn_wrapper_fixpt_l_0][plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_a0[plasma_nn_wrapper_fixpt_l_0 + plasma_nn_wrapper_fixpt_mul_temp_3] * plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0] = {{3{plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0][39]}}, plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0]};
        plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] + plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0][41:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l_0] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0][41], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0]};
      plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l_0] + plasma_nn_wrapper_fixpt_t_0[plasma_nn_wrapper_fixpt_l_0];
      if (43'sh00000000000 < plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0]) begin
        plasma_nn_wrapper_fixpt_tmp = plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp = 43'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_tmp;
      plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l_0][36:17];
      plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0] = 43'sh00000000000;
    end

    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l = 32'sd0; plasma_nn_wrapper_fixpt_l <= 32'sd4; plasma_nn_wrapper_fixpt_l = plasma_nn_wrapper_fixpt_l + 32'sd1) begin

      for(plasma_nn_wrapper_fixpt_k_1 = 32'sd0; plasma_nn_wrapper_fixpt_k_1 <= 32'sd4; plasma_nn_wrapper_fixpt_k_1 = plasma_nn_wrapper_fixpt_k_1 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_k_1] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l][42], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l]};
        plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k_1] = {1'b0, plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_cast_6 = plasma_nn_wrapper_fixpt_k_1;
        // CSD Encoding (5) : 0101; Cost (Adders) = 1
        plasma_nn_wrapper_fixpt_t_7[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1] = {plasma_nn_wrapper_fixpt_cast_6, 2'b00};
        plasma_nn_wrapper_fixpt_t_8[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1] = {{30{plasma_nn_wrapper_fixpt_t_7[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1][33]}}, plasma_nn_wrapper_fixpt_t_7[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_t_9[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1] = {{32{plasma_nn_wrapper_fixpt_cast_6[31]}}, plasma_nn_wrapper_fixpt_cast_6};
        plasma_nn_wrapper_fixpt_mul_temp_4 = plasma_nn_wrapper_fixpt_t_8[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1] + plasma_nn_wrapper_fixpt_t_9[plasma_nn_wrapper_fixpt_l][plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_a0_0[plasma_nn_wrapper_fixpt_l + plasma_nn_wrapper_fixpt_mul_temp_4] * plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1][39:0];
        plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1] = {{4{plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1][39]}}, plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_k_1] + plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_l] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l][42], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l]};
      plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_l] + plasma_nn_wrapper_fixpt_t_1[plasma_nn_wrapper_fixpt_l];
      if (44'sh00000000000 < plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l]) begin
        plasma_nn_wrapper_fixpt_tmp_0 = plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp_0 = 44'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_tmp_0;
      plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l][38:19];
      plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_l] = {plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l][18:0], 1'b0};
    end

    // Layer 3
    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l_1 = 32'sd0; plasma_nn_wrapper_fixpt_l_1 <= 32'sd4; plasma_nn_wrapper_fixpt_l_1 = plasma_nn_wrapper_fixpt_l_1 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = 43'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_2 = 32'sd0; plasma_nn_wrapper_fixpt_k_2 <= 32'sd4; plasma_nn_wrapper_fixpt_k_2 = plasma_nn_wrapper_fixpt_k_2 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_2] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][42], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
        plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_2] = {1'b0, plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_cast_7 = plasma_nn_wrapper_fixpt_k_2;
        // CSD Encoding (5) : 0101; Cost (Adders) = 1
        plasma_nn_wrapper_fixpt_t_10[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2] = {plasma_nn_wrapper_fixpt_cast_7, 2'b00};
        plasma_nn_wrapper_fixpt_t_11[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2] = {{30{plasma_nn_wrapper_fixpt_t_10[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2][33]}}, plasma_nn_wrapper_fixpt_t_10[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_t_12[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2] = {{32{plasma_nn_wrapper_fixpt_cast_7[31]}}, plasma_nn_wrapper_fixpt_cast_7};
        plasma_nn_wrapper_fixpt_mul_temp_5 = plasma_nn_wrapper_fixpt_t_11[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2] + plasma_nn_wrapper_fixpt_t_12[plasma_nn_wrapper_fixpt_l_1][plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_a0_1[plasma_nn_wrapper_fixpt_l_1 + plasma_nn_wrapper_fixpt_mul_temp_5] * plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2][39:0];
        plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2] = {{4{plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_k_2][39]}}, plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_2] + plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_k_2][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][42], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
      plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_l_1] + plasma_nn_wrapper_fixpt_t_2[plasma_nn_wrapper_fixpt_l_1];
      if (44'sh00000000000 < plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1]) begin
        plasma_nn_wrapper_fixpt_tmp_1 = plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp_1 = 44'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval_1[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_tmp_1;
      plasma_nn_wrapper_fixpt_cast_3[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_maxval_1[plasma_nn_wrapper_fixpt_l_1][38:19];
      plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_cast_3[plasma_nn_wrapper_fixpt_l_1][17:0], 2'b00};
    end

    // Layer 4
    // Output 1
    // Map Minimum and Maximum Output Reverse-Processing Function

    for(plasma_nn_wrapper_fixpt_l_2 = 32'sd0; plasma_nn_wrapper_fixpt_l_2 <= 32'sd1; plasma_nn_wrapper_fixpt_l_2 = plasma_nn_wrapper_fixpt_l_2 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2] = 43'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_3 = 32'sd0; plasma_nn_wrapper_fixpt_k_3 <= 32'sd4; plasma_nn_wrapper_fixpt_k_3 = plasma_nn_wrapper_fixpt_k_3 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_3] = {plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2][42], plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2]};
        plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_3] = {{31{plasma_nn_wrapper_fixpt_k_3[31]}}, {plasma_nn_wrapper_fixpt_k_3, 1'b0}};
        plasma_nn_wrapper_fixpt_cast_2[plasma_nn_wrapper_fixpt_k_3] = {1'b0, plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_k_3]};
        plasma_nn_wrapper_fixpt_mul_temp_2[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_a0_2[plasma_nn_wrapper_fixpt_l_2 + plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_3]] * plasma_nn_wrapper_fixpt_cast_2[plasma_nn_wrapper_fixpt_k_3];
        plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_mul_temp_2[plasma_nn_wrapper_fixpt_k_3][39:0];
        plasma_nn_wrapper_fixpt_add_cast_15[plasma_nn_wrapper_fixpt_k_3] = {{4{plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_k_3][39]}}, plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_k_3]};
        plasma_nn_wrapper_fixpt_add_temp_3[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_3] + plasma_nn_wrapper_fixpt_add_cast_15[plasma_nn_wrapper_fixpt_k_3];
        plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_temp_3[plasma_nn_wrapper_fixpt_k_3][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2][42], plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_l_2] + plasma_nn_wrapper_fixpt_t_3[plasma_nn_wrapper_fixpt_l_2];
      plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_l_2][38:19];
      plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_2] = {{3{plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2][19]}}, plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_c_9[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_2] - 23'sb11100000000000000000000;
      plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_c_9[plasma_nn_wrapper_fixpt_l_2][21:2];
      plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_2];
      plasma_nn_wrapper_fixpt_add_cast_16[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2][19], plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_c_10[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_cast_16[plasma_nn_wrapper_fixpt_l_2] + 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_cast_4[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_c_10[plasma_nn_wrapper_fixpt_l_2][19:0];
      plasma_nn_wrapper_fixpt_y1[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_cast_4[plasma_nn_wrapper_fixpt_l_2][17:0], 2'b00};
    end

    y1_1_1 = {{2{plasma_nn_wrapper_fixpt_y1[0][19]}}, plasma_nn_wrapper_fixpt_y1[0][19:2]};
    y1_2_1 = {{2{plasma_nn_wrapper_fixpt_y1[1][19]}}, plasma_nn_wrapper_fixpt_y1[1][19:2]};
  end



  assign y1_1 = y1_1_1;

  assign y1_2 = y1_2_1;

endmodule  // plasma_nn_wrapper_fixpt

