function [hw_ctrl] = initialize_fpga_ctrl(data_save_file, params, codegen_dir)
% function to run a closed-loop simulation of the msMPC on hardware. the input
% arguments to this function are considered to be Python types and must be
% converted to the appropriate MATLAB types first.
%
% params - the params argument parameterizes the closed-loop implementation
%       which currently supports the parameters related to the DNN
%       construction (number of nodes H and number of hidden layers L),
%       parameters related to hardware implementation (option to unroll
%       loops and fixed point word length)
% data_save_file - the data_save_file argument denotes the location of the
%       data for training a DNN (generated by either gathering open-loop or
%       closed-loop data of an MPC system)
%
% Name-Value Pair Arguments:
%
params = struct(params);
data_save_file = char(data_save_file);

% convert required arguments from Python types to MATLAB types
addpath(genpath('./config'), genpath('./utils'),genpath('../Model_ID'),genpath('./codegen_helpers'),genpath(codegen_dir))

%% build hw controller
dnn_data = load(data_save_file);
sf.input_min = dnn_data.input_min;
sf.input_max = dnn_data.input_max;
sf.output_min = dnn_data.output_min;
sf.output_max = dnn_data.output_max;

hw_ctrl = HWController('plasma_nn_wrapper', 'test_fullDNN', sf);
hw_ctrl = hw_ctrl.setCodegenDir(codegen_dir);
hw_ctrl = hw_ctrl.loadController(params);

[out, hw_ctrl] = hw_ctrl.getControlInput(zeros(3,1))
