function plasma_nn_wrapper_fixpt_programFPGA 
%plasma_nn_wrapper_fixpt_programFPGA is a filWizard generated function used to load the
%   programming file for the 'plasma_nn_wrapper_fixpt' HDL in the 'Zybo Zynq-7000 - Copy' FPGA board. 
%
%   File Name: plasma_nn_wrapper_fixpt_programFPGA.m
%   Created: 04-Oct-2023 00:34:46
% 
%   Generated by FIL Wizard

filProgramFPGA('Xilinx Vivado', ...
               '/home/kimberlychan/Desktop/DNN_Generality/matlab_v3/hdlcoder_fullDNN/codegen/plasma_nn_wrapper/fil/plasma_nn_wrapper_fixpt_fil/plasma_nn_wrapper_fixpt_fil.bit',...
               2);


end




