%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [y1_1,y1_2] = plasma_nn_wrapper_wrapper_fixpt(x1_1,x1_2,x1_3)
    fm = get_fimath();
    x1_1_in = fi( x1_1, 1, 22, 20, fm );
    x1_2_in = fi( x1_2, 1, 22, 20, fm );
    x1_3_in = fi( x1_3, 1, 3, 0, fm );
    [y1_1_out,y1_2_out] = plasma_nn_wrapper_fixpt( x1_1_in, x1_2_in, x1_3_in );
    y1_1 = double( y1_1_out );
    y1_2 = double( y1_2_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
