// -------------------------------------------------------------
// 
// File Name: /home/kimberlychan/Desktop/DNN_Generality/matlab_v3/hdlcoder_fullDNN/codegen/plasma_nn_wrapper/hdlsrc/plasma_nn_wrapper_fixpt.v
// Created: 2023-10-04 00:25:57
// 
// Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: plasma_nn_wrapper_fixpt
// Source Path: plasma_nn_wrapper_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module plasma_nn_wrapper_fixpt
          (x1_1,
           x1_2,
           x1_3,
           y1_1,
           y1_2);


  input   signed [19:0] x1_1;  // sfix20_En18
  input   signed [19:0] x1_2;  // sfix20_En18
  input   signed [19:0] x1_3;  // sfix20_En18
  output  signed [19:0] y1_1;  // sfix20_En18
  output  signed [19:0] y1_2;  // sfix20_En18


  reg signed [19:0] y1_1_1;  // sfix20_En18
  reg signed [19:0] y1_2_1;  // sfix20_En18
  reg signed [19:0] plasma_nn_wrapper_fixpt_x1 [0:2];  // sfix20_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c [0:2];  // sfix21_En18 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y [0:2];  // sfix20_En17 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_0 [0:2];  // sfix21_En17 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y_0 [0:2];  // sfix20_En17 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_1 [0:2];  // sfix21_En17 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_xp1 [0:2];  // sfix20_En18 [3]
  reg signed [41:0] plasma_nn_wrapper_fixpt_c_2 [0:7];  // sfix42_En36 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_3 [0:7];  // sfix43_En36 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_maxval [0:7];  // sfix43_En36 [8]
  reg [19:0] plasma_nn_wrapper_fixpt_a1 [0:7];  // ufix20_En18 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_4 [0:7];  // sfix43_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_c_5 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_maxval_0 [0:7];  // sfix44_En36 [8]
  reg [19:0] plasma_nn_wrapper_fixpt_a2 [0:7];  // ufix20_En18 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_6 [0:7];  // sfix43_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_c_7 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_maxval_1 [0:7];  // sfix44_En36 [8]
  reg [19:0] plasma_nn_wrapper_fixpt_a3 [0:7];  // ufix20_En17 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_c_8 [0:1];  // sfix43_En35 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a4 [0:1];  // sfix20_En18 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_9 [0:1];  // sfix21_En18 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a [0:1];  // sfix20_En17 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_x [0:1];  // sfix20_En17 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_10 [0:1];  // sfix21_En17 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_y1 [0:1];  // sfix20_En18 [2]
  reg signed [31:0] plasma_nn_wrapper_fixpt_k;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_0;  // int32
  reg signed [42:0] plasma_nn_wrapper_fixpt_tmp;  // sfix43_En36
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_1;  // int32
  reg signed [43:0] plasma_nn_wrapper_fixpt_tmp_0;  // sfix44_En36
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_2;  // int32
  reg signed [43:0] plasma_nn_wrapper_fixpt_tmp_1;  // sfix44_En36
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_3;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_0;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_1;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_2;  // int32
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0 [0:23];  // sfix20_En18 [24]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_0 [0:63];  // sfix20_En18 [64]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_1 [0:63];  // sfix20_En18 [64]
  reg signed [19:0] plasma_nn_wrapper_fixpt_a0_2 [0:15];  // sfix20_En18 [16]
  reg signed [42:0] plasma_nn_wrapper_fixpt_t_0 [0:7];  // sfix43_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_1 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_2 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_t_3 [0:1];  // sfix44_En35 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_sub_cast [0:2];  // sfix21_En18 [3]
  reg signed [20:0] plasma_nn_wrapper_fixpt_add_cast [0:2];  // sfix21_En17 [3]
  reg signed [19:0] plasma_nn_wrapper_fixpt_cast [0:2];  // sfix20_En17 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_0 [0:7];  // sfix43_En36 [8]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_1 [0:2];  // sfix43_En36 [3]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_2 [0:2];  // sfix64 [3]
  reg signed [39:0] plasma_nn_wrapper_fixpt_mul_temp [0:2];  // sfix40_En36 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_cast_3 [0:2];  // sfix43_En36 [3]
  reg signed [42:0] plasma_nn_wrapper_fixpt_add_temp [0:2];  // sfix43_En36 [3]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_4 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_5 [0:7];  // sfix44_En36 [8]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_6 [0:7];  // sfix64 [8]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast_0 [0:7];  // sfix21_En18 [8]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_0 [0:7];  // sfix41_En36 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_7 [0:7];  // sfix40_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_8 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_0 [0:7];  // sfix44_En36 [8]
  reg [19:0] plasma_nn_wrapper_fixpt_cast_1 [0:7];  // ufix20_En17 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_9 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_10 [0:7];  // sfix44_En36 [8]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_11 [0:7];  // sfix64 [8]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast_2 [0:7];  // sfix21_En18 [8]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_1 [0:7];  // sfix41_En36 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_12 [0:7];  // sfix40_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_13 [0:7];  // sfix44_En36 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_1 [0:7];  // sfix44_En36 [8]
  reg [19:0] plasma_nn_wrapper_fixpt_cast_3 [0:7];  // ufix20_En17 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_14 [0:1];  // sfix44_En35 [2]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_2 [0:1];  // sfix44_En35 [2]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_15 [0:7];  // sfix44_En35 [8]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_16 [0:7];  // sfix64 [8]
  reg signed [20:0] plasma_nn_wrapper_fixpt_cast_4 [0:7];  // sfix21_En17 [8]
  reg signed [40:0] plasma_nn_wrapper_fixpt_mul_temp_2 [0:7];  // sfix41_En35 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_17 [0:7];  // sfix40_En35 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_cast_18 [0:7];  // sfix44_En35 [8]
  reg signed [43:0] plasma_nn_wrapper_fixpt_add_temp_3 [0:7];  // sfix44_En35 [8]
  reg signed [20:0] plasma_nn_wrapper_fixpt_sub_cast_0 [0:1];  // sfix21_En18 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_add_cast_19 [0:1];  // sfix21_En17 [2]
  reg signed [19:0] plasma_nn_wrapper_fixpt_cast_5 [0:1];  // sfix20_En17 [2]


  always @(x1_1, x1_2, x1_3) begin
    plasma_nn_wrapper_fixpt_a0[0] = 20'sb10101101000110010111;
    plasma_nn_wrapper_fixpt_a0[1] = 20'sb00110010011010001110;
    plasma_nn_wrapper_fixpt_a0[2] = 20'sb11111011101100011100;
    plasma_nn_wrapper_fixpt_a0[3] = 20'sb00010011010001100011;
    plasma_nn_wrapper_fixpt_a0[4] = 20'sb11101101011001011000;
    plasma_nn_wrapper_fixpt_a0[5] = 20'sb11111011110001110111;
    plasma_nn_wrapper_fixpt_a0[6] = 20'sb10100101011110000111;
    plasma_nn_wrapper_fixpt_a0[7] = 20'sb11001110010100010000;
    plasma_nn_wrapper_fixpt_a0[8] = 20'sb11100100000001100111;
    plasma_nn_wrapper_fixpt_a0[9] = 20'sb11111110110011011111;
    plasma_nn_wrapper_fixpt_a0[10] = 20'sb00011100010100100101;
    plasma_nn_wrapper_fixpt_a0[11] = 20'sb11111101000101111111;
    plasma_nn_wrapper_fixpt_a0[12] = 20'sb11111001101110001111;
    plasma_nn_wrapper_fixpt_a0[13] = 20'sb00000000010011100111;
    plasma_nn_wrapper_fixpt_a0[14] = 20'sb11111111001100101000;
    plasma_nn_wrapper_fixpt_a0[15] = 20'sb11110111100000001010;
    plasma_nn_wrapper_fixpt_a0[16] = 20'sb01000010100101101100;
    plasma_nn_wrapper_fixpt_a0[17] = 20'sb11000111111010011101;
    plasma_nn_wrapper_fixpt_a0[18] = 20'sb00000000000111000100;
    plasma_nn_wrapper_fixpt_a0[19] = 20'sb11100110100000011001;
    plasma_nn_wrapper_fixpt_a0[20] = 20'sb00000101001001001011;
    plasma_nn_wrapper_fixpt_a0[21] = 20'sb11011111110110001101;
    plasma_nn_wrapper_fixpt_a0[22] = 20'sb11001001110101101001;
    plasma_nn_wrapper_fixpt_a0[23] = 20'sb10110110100001010011;
    plasma_nn_wrapper_fixpt_a0_0[0] = 20'sb00001111000111010001;
    plasma_nn_wrapper_fixpt_a0_0[1] = 20'sb11111011010101101100;
    plasma_nn_wrapper_fixpt_a0_0[2] = 20'sb01000000111010111000;
    plasma_nn_wrapper_fixpt_a0_0[3] = 20'sb00001001101110010001;
    plasma_nn_wrapper_fixpt_a0_0[4] = 20'sb00010010110101111000;
    plasma_nn_wrapper_fixpt_a0_0[5] = 20'sb01000110011011111100;
    plasma_nn_wrapper_fixpt_a0_0[6] = 20'sb00110010100100011111;
    plasma_nn_wrapper_fixpt_a0_0[7] = 20'sb11110110011000110011;
    plasma_nn_wrapper_fixpt_a0_0[8] = 20'sb00101100100000000000;
    plasma_nn_wrapper_fixpt_a0_0[9] = 20'sb00001010111010000111;
    plasma_nn_wrapper_fixpt_a0_0[10] = 20'sb00000101010101000111;
    plasma_nn_wrapper_fixpt_a0_0[11] = 20'sb01101011010001010111;
    plasma_nn_wrapper_fixpt_a0_0[12] = 20'sb11110010101001100110;
    plasma_nn_wrapper_fixpt_a0_0[13] = 20'sb11110111011100100111;
    plasma_nn_wrapper_fixpt_a0_0[14] = 20'sb11110101000011001111;
    plasma_nn_wrapper_fixpt_a0_0[15] = 20'sb11100101100011100001;
    plasma_nn_wrapper_fixpt_a0_0[16] = 20'sb00001011000110000000;
    plasma_nn_wrapper_fixpt_a0_0[17] = 20'sb00000000001000000010;
    plasma_nn_wrapper_fixpt_a0_0[18] = 20'sb11011100111101000010;
    plasma_nn_wrapper_fixpt_a0_0[19] = 20'sb11111011001001011111;
    plasma_nn_wrapper_fixpt_a0_0[20] = 20'sb11001011000011110001;
    plasma_nn_wrapper_fixpt_a0_0[21] = 20'sb00001101001100001111;
    plasma_nn_wrapper_fixpt_a0_0[22] = 20'sb00010100111010101110;
    plasma_nn_wrapper_fixpt_a0_0[23] = 20'sb11101101100111010110;
    plasma_nn_wrapper_fixpt_a0_0[24] = 20'sb11101111110001111111;
    plasma_nn_wrapper_fixpt_a0_0[25] = 20'sb00101000101000110001;
    plasma_nn_wrapper_fixpt_a0_0[26] = 20'sb00000110011100001100;
    plasma_nn_wrapper_fixpt_a0_0[27] = 20'sb00010000110001101100;
    plasma_nn_wrapper_fixpt_a0_0[28] = 20'sb11010111010011001111;
    plasma_nn_wrapper_fixpt_a0_0[29] = 20'sb00010010100010011100;
    plasma_nn_wrapper_fixpt_a0_0[30] = 20'sb11011111000111111010;
    plasma_nn_wrapper_fixpt_a0_0[31] = 20'sb11001000000001101000;
    plasma_nn_wrapper_fixpt_a0_0[32] = 20'sb11010001010111110110;
    plasma_nn_wrapper_fixpt_a0_0[33] = 20'sb11001001100101000110;
    plasma_nn_wrapper_fixpt_a0_0[34] = 20'sb00100000010010010001;
    plasma_nn_wrapper_fixpt_a0_0[35] = 20'sb11100111100101011011;
    plasma_nn_wrapper_fixpt_a0_0[36] = 20'sb00100000100111011111;
    plasma_nn_wrapper_fixpt_a0_0[37] = 20'sb11111001011010001010;
    plasma_nn_wrapper_fixpt_a0_0[38] = 20'sb00100101000110011101;
    plasma_nn_wrapper_fixpt_a0_0[39] = 20'sb11001110010011110001;
    plasma_nn_wrapper_fixpt_a0_0[40] = 20'sb11101100011101011011;
    plasma_nn_wrapper_fixpt_a0_0[41] = 20'sb11111010101111000010;
    plasma_nn_wrapper_fixpt_a0_0[42] = 20'sb00110011110001111000;
    plasma_nn_wrapper_fixpt_a0_0[43] = 20'sb00000011101001111101;
    plasma_nn_wrapper_fixpt_a0_0[44] = 20'sb00000000101100010110;
    plasma_nn_wrapper_fixpt_a0_0[45] = 20'sb11011000100001110101;
    plasma_nn_wrapper_fixpt_a0_0[46] = 20'sb11101101011001011010;
    plasma_nn_wrapper_fixpt_a0_0[47] = 20'sb00111110100000100101;
    plasma_nn_wrapper_fixpt_a0_0[48] = 20'sb01010001011011111111;
    plasma_nn_wrapper_fixpt_a0_0[49] = 20'sb11000010101001011111;
    plasma_nn_wrapper_fixpt_a0_0[50] = 20'sb00001100111100011100;
    plasma_nn_wrapper_fixpt_a0_0[51] = 20'sb11101000001001111101;
    plasma_nn_wrapper_fixpt_a0_0[52] = 20'sb11100101111010001001;
    plasma_nn_wrapper_fixpt_a0_0[53] = 20'sb11110011010010000000;
    plasma_nn_wrapper_fixpt_a0_0[54] = 20'sb00011010110001001001;
    plasma_nn_wrapper_fixpt_a0_0[55] = 20'sb11000011000111011001;
    plasma_nn_wrapper_fixpt_a0_0[56] = 20'sb00010011001010111011;
    plasma_nn_wrapper_fixpt_a0_0[57] = 20'sb00000000110111110101;
    plasma_nn_wrapper_fixpt_a0_0[58] = 20'sb11010000010111101101;
    plasma_nn_wrapper_fixpt_a0_0[59] = 20'sb10101101011001000011;
    plasma_nn_wrapper_fixpt_a0_0[60] = 20'sb10110001101001001110;
    plasma_nn_wrapper_fixpt_a0_0[61] = 20'sb00010100000000111010;
    plasma_nn_wrapper_fixpt_a0_0[62] = 20'sb00001001100111011111;
    plasma_nn_wrapper_fixpt_a0_0[63] = 20'sb00110110111111100000;
    plasma_nn_wrapper_fixpt_a0_1[0] = 20'sb00001010001100100111;
    plasma_nn_wrapper_fixpt_a0_1[1] = 20'sb11000111011011000101;
    plasma_nn_wrapper_fixpt_a0_1[2] = 20'sb00010101101010110011;
    plasma_nn_wrapper_fixpt_a0_1[3] = 20'sb11011001111001100100;
    plasma_nn_wrapper_fixpt_a0_1[4] = 20'sb00100111010001010000;
    plasma_nn_wrapper_fixpt_a0_1[5] = 20'sb11101010111111111100;
    plasma_nn_wrapper_fixpt_a0_1[6] = 20'sb11010010011100010001;
    plasma_nn_wrapper_fixpt_a0_1[7] = 20'sb00101010001100001000;
    plasma_nn_wrapper_fixpt_a0_1[8] = 20'sb00010101100101000011;
    plasma_nn_wrapper_fixpt_a0_1[9] = 20'sb00000000010111110011;
    plasma_nn_wrapper_fixpt_a0_1[10] = 20'sb11110011101111000001;
    plasma_nn_wrapper_fixpt_a0_1[11] = 20'sb00000111101101011101;
    plasma_nn_wrapper_fixpt_a0_1[12] = 20'sb11100011101000101110;
    plasma_nn_wrapper_fixpt_a0_1[13] = 20'sb00001001000011110101;
    plasma_nn_wrapper_fixpt_a0_1[14] = 20'sb00101011001101001110;
    plasma_nn_wrapper_fixpt_a0_1[15] = 20'sb00111100111110001010;
    plasma_nn_wrapper_fixpt_a0_1[16] = 20'sb00111110110011011100;
    plasma_nn_wrapper_fixpt_a0_1[17] = 20'sb11100110100010111111;
    plasma_nn_wrapper_fixpt_a0_1[18] = 20'sb01001111010000010111;
    plasma_nn_wrapper_fixpt_a0_1[19] = 20'sb00101000110100010100;
    plasma_nn_wrapper_fixpt_a0_1[20] = 20'sb11011111100010001100;
    plasma_nn_wrapper_fixpt_a0_1[21] = 20'sb11010000010111010111;
    plasma_nn_wrapper_fixpt_a0_1[22] = 20'sb11110000100111100000;
    plasma_nn_wrapper_fixpt_a0_1[23] = 20'sb00010110111111010100;
    plasma_nn_wrapper_fixpt_a0_1[24] = 20'sb00111111111000110011;
    plasma_nn_wrapper_fixpt_a0_1[25] = 20'sb00010110111000101011;
    plasma_nn_wrapper_fixpt_a0_1[26] = 20'sb11011001011010110000;
    plasma_nn_wrapper_fixpt_a0_1[27] = 20'sb10110110110011101010;
    plasma_nn_wrapper_fixpt_a0_1[28] = 20'sb01100001001010010001;
    plasma_nn_wrapper_fixpt_a0_1[29] = 20'sb11100111001011000000;
    plasma_nn_wrapper_fixpt_a0_1[30] = 20'sb11101001110000010001;
    plasma_nn_wrapper_fixpt_a0_1[31] = 20'sb11010100101101011011;
    plasma_nn_wrapper_fixpt_a0_1[32] = 20'sb00010100111001110111;
    plasma_nn_wrapper_fixpt_a0_1[33] = 20'sb00011010010000100011;
    plasma_nn_wrapper_fixpt_a0_1[34] = 20'sb01000110101010010000;
    plasma_nn_wrapper_fixpt_a0_1[35] = 20'sb10111001111100110000;
    plasma_nn_wrapper_fixpt_a0_1[36] = 20'sb00100100100001110001;
    plasma_nn_wrapper_fixpt_a0_1[37] = 20'sb11000110010111011100;
    plasma_nn_wrapper_fixpt_a0_1[38] = 20'sb11111011111111100010;
    plasma_nn_wrapper_fixpt_a0_1[39] = 20'sb11111001010110101001;
    plasma_nn_wrapper_fixpt_a0_1[40] = 20'sb00100000110100000110;
    plasma_nn_wrapper_fixpt_a0_1[41] = 20'sb00100000011110100100;
    plasma_nn_wrapper_fixpt_a0_1[42] = 20'sb11011010100110001001;
    plasma_nn_wrapper_fixpt_a0_1[43] = 20'sb10110010101100000111;
    plasma_nn_wrapper_fixpt_a0_1[44] = 20'sb00000011111000110101;
    plasma_nn_wrapper_fixpt_a0_1[45] = 20'sb00101001110010111001;
    plasma_nn_wrapper_fixpt_a0_1[46] = 20'sb11101101011000111111;
    plasma_nn_wrapper_fixpt_a0_1[47] = 20'sb11101010011111100110;
    plasma_nn_wrapper_fixpt_a0_1[48] = 20'sb11011101110011100110;
    plasma_nn_wrapper_fixpt_a0_1[49] = 20'sb11101100111011011100;
    plasma_nn_wrapper_fixpt_a0_1[50] = 20'sb11100111101010100010;
    plasma_nn_wrapper_fixpt_a0_1[51] = 20'sb11111011000101011111;
    plasma_nn_wrapper_fixpt_a0_1[52] = 20'sb00001000101101110100;
    plasma_nn_wrapper_fixpt_a0_1[53] = 20'sb11000001001001011010;
    plasma_nn_wrapper_fixpt_a0_1[54] = 20'sb00011001000101101100;
    plasma_nn_wrapper_fixpt_a0_1[55] = 20'sb00111010001101011001;
    plasma_nn_wrapper_fixpt_a0_1[56] = 20'sb11100010111100110100;
    plasma_nn_wrapper_fixpt_a0_1[57] = 20'sb11011000001111101000;
    plasma_nn_wrapper_fixpt_a0_1[58] = 20'sb10110101100011111110;
    plasma_nn_wrapper_fixpt_a0_1[59] = 20'sb11111010010010110010;
    plasma_nn_wrapper_fixpt_a0_1[60] = 20'sb00010010110110000100;
    plasma_nn_wrapper_fixpt_a0_1[61] = 20'sb00110001010100000011;
    plasma_nn_wrapper_fixpt_a0_1[62] = 20'sb00111010100010101001;
    plasma_nn_wrapper_fixpt_a0_1[63] = 20'sb00101010100100101010;
    plasma_nn_wrapper_fixpt_a0_2[0] = 20'sb11001000101111101010;
    plasma_nn_wrapper_fixpt_a0_2[1] = 20'sb00110010010001001101;
    plasma_nn_wrapper_fixpt_a0_2[2] = 20'sb11001111011010000111;
    plasma_nn_wrapper_fixpt_a0_2[3] = 20'sb11000110001000000010;
    plasma_nn_wrapper_fixpt_a0_2[4] = 20'sb11110110111011000110;
    plasma_nn_wrapper_fixpt_a0_2[5] = 20'sb01001010011010101111;
    plasma_nn_wrapper_fixpt_a0_2[6] = 20'sb01000101101110111110;
    plasma_nn_wrapper_fixpt_a0_2[7] = 20'sb10111111100010010001;
    plasma_nn_wrapper_fixpt_a0_2[8] = 20'sb11000110000100010001;
    plasma_nn_wrapper_fixpt_a0_2[9] = 20'sb00110100001111101010;
    plasma_nn_wrapper_fixpt_a0_2[10] = 20'sb11101110101101001011;
    plasma_nn_wrapper_fixpt_a0_2[11] = 20'sb00000001110001111011;
    plasma_nn_wrapper_fixpt_a0_2[12] = 20'sb00110111101111111010;
    plasma_nn_wrapper_fixpt_a0_2[13] = 20'sb01000010111110110000;
    plasma_nn_wrapper_fixpt_a0_2[14] = 20'sb00100011010100100010;
    plasma_nn_wrapper_fixpt_a0_2[15] = 20'sb11100010010110111001;
    plasma_nn_wrapper_fixpt_t_0[0] = 43'sh005B8F80000;
    plasma_nn_wrapper_fixpt_t_0[1] = 43'sh7FF89C00000;
    plasma_nn_wrapper_fixpt_t_0[2] = 43'sh0065CF80000;
    plasma_nn_wrapper_fixpt_t_0[3] = 43'sh7F3E0300000;
    plasma_nn_wrapper_fixpt_t_0[4] = 43'sh7F571C40000;
    plasma_nn_wrapper_fixpt_t_0[5] = 43'sh7F040D40000;
    plasma_nn_wrapper_fixpt_t_0[6] = 43'sh005A6B00000;
    plasma_nn_wrapper_fixpt_t_0[7] = 43'sh01A0F380000;
    plasma_nn_wrapper_fixpt_t_1[0] = 44'shFFC10640000;
    plasma_nn_wrapper_fixpt_t_1[1] = 44'shFF9FAFE0000;
    plasma_nn_wrapper_fixpt_t_1[2] = 44'sh0056BE60000;
    plasma_nn_wrapper_fixpt_t_1[3] = 44'sh008A9DA0000;
    plasma_nn_wrapper_fixpt_t_1[4] = 44'sh004A7CE0000;
    plasma_nn_wrapper_fixpt_t_1[5] = 44'shFF3BD080000;
    plasma_nn_wrapper_fixpt_t_1[6] = 44'shFFFD4A80000;
    plasma_nn_wrapper_fixpt_t_1[7] = 44'sh00A60980000;
    plasma_nn_wrapper_fixpt_t_2[0] = 44'sh00ADBD40000;
    plasma_nn_wrapper_fixpt_t_2[1] = 44'shFF84D340000;
    plasma_nn_wrapper_fixpt_t_2[2] = 44'shFFECAC40000;
    plasma_nn_wrapper_fixpt_t_2[3] = 44'sh00D93FC0000;
    plasma_nn_wrapper_fixpt_t_2[4] = 44'shFEC1F740000;
    plasma_nn_wrapper_fixpt_t_2[5] = 44'shFF071280000;
    plasma_nn_wrapper_fixpt_t_2[6] = 44'shFF9AA6C0000;
    plasma_nn_wrapper_fixpt_t_2[7] = 44'shFFD71BC0000;
    plasma_nn_wrapper_fixpt_t_3[0] = 44'sh00007300000;
    plasma_nn_wrapper_fixpt_t_3[1] = 44'shFFDFF198000;
    plasma_nn_wrapper_fixpt_tmp = 43'sh00000000000;
    plasma_nn_wrapper_fixpt_tmp_0 = 44'sh00000000000;
    plasma_nn_wrapper_fixpt_tmp_1 = 44'sh00000000000;
    //HDL code generation from MATLAB function: plasma_nn_wrapper_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    plasma_nn_wrapper_fixpt_x1[0] = x1_1;
    plasma_nn_wrapper_fixpt_x1[1] = x1_2;
    plasma_nn_wrapper_fixpt_x1[2] = x1_3;
    //PLASMA_NN neural network simulation function.
    //
    // Auto-generated by MATLAB, 04-Oct-2023 00:25:18.
    // 
    // [y1] = plasma_nn(x1) takes these arguments:
    //   x = 3xQ matrix, input #1
    // and returns:
    //   y = 2xQ matrix, output #1
    // where Q is the number of samples.
    // ===== NEURAL NETWORK CONSTANTS =====
    // Input 1
    // Layer 1
    // Layer 2
    // Layer 3
    // Layer 4
    // Output 1
    // ===== SIMULATION ========
    // Dimensions
    // samples
    // Input 1
    // ===== MODULE FUNCTIONS ========
    // Map Minimum and Maximum Input Processing Function

    for(plasma_nn_wrapper_fixpt_k = 32'sd0; plasma_nn_wrapper_fixpt_k <= 32'sd2; plasma_nn_wrapper_fixpt_k = plasma_nn_wrapper_fixpt_k + 32'sd1) begin
      plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] - 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k][20:1];
      plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k][19:0];
      plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k][19], plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] + 21'sb111100000000000000000;
      plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k][19:0];
      plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k][18:0], 1'b0};
    end

    // Layer 1
    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l = 32'sd0; plasma_nn_wrapper_fixpt_l <= 32'sd7; plasma_nn_wrapper_fixpt_l = plasma_nn_wrapper_fixpt_l + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l] = 42'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_0 = 32'sd0; plasma_nn_wrapper_fixpt_k_0 <= 32'sd2; plasma_nn_wrapper_fixpt_k_0 = plasma_nn_wrapper_fixpt_k_0 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l][41], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l]};
        plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0] = {{29{plasma_nn_wrapper_fixpt_k_0[31]}}, {plasma_nn_wrapper_fixpt_k_0, 3'b000}};
        plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_a0[plasma_nn_wrapper_fixpt_l + plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0]] * plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_k_0] = {{3{plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0][39]}}, plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0]};
        plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] + plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0][41:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l][41], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l]};
      plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l] + plasma_nn_wrapper_fixpt_t_0[plasma_nn_wrapper_fixpt_l];
      if (43'sh00000000000 < plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l]) begin
        plasma_nn_wrapper_fixpt_tmp = plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp = 43'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_tmp;
      plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l][38:19];
      plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_l] = {plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l][18:0], 1'b0};
    end

    // Layer 2
    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l_0 = 32'sd0; plasma_nn_wrapper_fixpt_l_0 <= 32'sd7; plasma_nn_wrapper_fixpt_l_0 = plasma_nn_wrapper_fixpt_l_0 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0] = 43'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_1 = 32'sd0; plasma_nn_wrapper_fixpt_k_1 <= 32'sd7; plasma_nn_wrapper_fixpt_k_1 = plasma_nn_wrapper_fixpt_k_1 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0][42], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0]};
        plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1] = {{29{plasma_nn_wrapper_fixpt_k_1[31]}}, {plasma_nn_wrapper_fixpt_k_1, 3'b000}};
        plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_1] = {1'b0, plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_a0_0[plasma_nn_wrapper_fixpt_l_0 + plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1]] * plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1][39:0];
        plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_1] = {{4{plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1][39]}}, plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1] + plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_l_0] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0][42], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0]};
      plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_l_0] + plasma_nn_wrapper_fixpt_t_1[plasma_nn_wrapper_fixpt_l_0];
      if (44'sh00000000000 < plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l_0]) begin
        plasma_nn_wrapper_fixpt_tmp_0 = plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l_0];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp_0 = 44'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_tmp_0;
      plasma_nn_wrapper_fixpt_cast_3[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l_0][38:19];
      plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_l_0] = {plasma_nn_wrapper_fixpt_cast_3[plasma_nn_wrapper_fixpt_l_0][18:0], 1'b0};
    end

    // Layer 3
    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l_1 = 32'sd0; plasma_nn_wrapper_fixpt_l_1 <= 32'sd7; plasma_nn_wrapper_fixpt_l_1 = plasma_nn_wrapper_fixpt_l_1 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = 43'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_2 = 32'sd0; plasma_nn_wrapper_fixpt_k_2 <= 32'sd7; plasma_nn_wrapper_fixpt_k_2 = plasma_nn_wrapper_fixpt_k_2 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][42], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
        plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_k_2] = {{29{plasma_nn_wrapper_fixpt_k_2[31]}}, {plasma_nn_wrapper_fixpt_k_2, 3'b000}};
        plasma_nn_wrapper_fixpt_cast_2[plasma_nn_wrapper_fixpt_k_2] = {1'b0, plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_a0_1[plasma_nn_wrapper_fixpt_l_1 + plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_k_2]] * plasma_nn_wrapper_fixpt_cast_2[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2][39:0];
        plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_2] = {{4{plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2][39]}}, plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2] + plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_k_2][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][42], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
      plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_l_1] + plasma_nn_wrapper_fixpt_t_2[plasma_nn_wrapper_fixpt_l_1];
      if (44'sh00000000000 < plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1]) begin
        plasma_nn_wrapper_fixpt_tmp_1 = plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp_1 = 44'sh00000000000;
      end
      plasma_nn_wrapper_fixpt_maxval_1[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_tmp_1;
      plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_maxval_1[plasma_nn_wrapper_fixpt_l_1][38:19];
    end

    // Layer 4
    // Output 1
    // Map Minimum and Maximum Output Reverse-Processing Function

    for(plasma_nn_wrapper_fixpt_l_2 = 32'sd0; plasma_nn_wrapper_fixpt_l_2 <= 32'sd1; plasma_nn_wrapper_fixpt_l_2 = plasma_nn_wrapper_fixpt_l_2 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2] = 43'sh00000000000;

      for(plasma_nn_wrapper_fixpt_k_3 = 32'sd0; plasma_nn_wrapper_fixpt_k_3 <= 32'sd7; plasma_nn_wrapper_fixpt_k_3 = plasma_nn_wrapper_fixpt_k_3 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_15[plasma_nn_wrapper_fixpt_k_3] = {plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2][42], plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2]};
        plasma_nn_wrapper_fixpt_add_cast_16[plasma_nn_wrapper_fixpt_k_3] = {{31{plasma_nn_wrapper_fixpt_k_3[31]}}, {plasma_nn_wrapper_fixpt_k_3, 1'b0}};
        plasma_nn_wrapper_fixpt_cast_4[plasma_nn_wrapper_fixpt_k_3] = {1'b0, plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_k_3]};
        plasma_nn_wrapper_fixpt_mul_temp_2[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_a0_2[plasma_nn_wrapper_fixpt_l_2 + plasma_nn_wrapper_fixpt_add_cast_16[plasma_nn_wrapper_fixpt_k_3]] * plasma_nn_wrapper_fixpt_cast_4[plasma_nn_wrapper_fixpt_k_3];
        plasma_nn_wrapper_fixpt_add_cast_17[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_mul_temp_2[plasma_nn_wrapper_fixpt_k_3][39:0];
        plasma_nn_wrapper_fixpt_add_cast_18[plasma_nn_wrapper_fixpt_k_3] = {{4{plasma_nn_wrapper_fixpt_add_cast_17[plasma_nn_wrapper_fixpt_k_3][39]}}, plasma_nn_wrapper_fixpt_add_cast_17[plasma_nn_wrapper_fixpt_k_3]};
        plasma_nn_wrapper_fixpt_add_temp_3[plasma_nn_wrapper_fixpt_k_3] = plasma_nn_wrapper_fixpt_add_cast_15[plasma_nn_wrapper_fixpt_k_3] + plasma_nn_wrapper_fixpt_add_cast_18[plasma_nn_wrapper_fixpt_k_3];
        plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_temp_3[plasma_nn_wrapper_fixpt_k_3][42:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2][42], plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_l_2] + plasma_nn_wrapper_fixpt_t_3[plasma_nn_wrapper_fixpt_l_2];
      plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_l_2][36:17];
      plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2][19], plasma_nn_wrapper_fixpt_a4[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_c_9[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_2] - 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_c_9[plasma_nn_wrapper_fixpt_l_2][20:1];
      plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_2];
      plasma_nn_wrapper_fixpt_add_cast_19[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2][19], plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_2]};
      plasma_nn_wrapper_fixpt_c_10[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_add_cast_19[plasma_nn_wrapper_fixpt_l_2] + 21'sb111100000000000000000;
      plasma_nn_wrapper_fixpt_cast_5[plasma_nn_wrapper_fixpt_l_2] = plasma_nn_wrapper_fixpt_c_10[plasma_nn_wrapper_fixpt_l_2][19:0];
      plasma_nn_wrapper_fixpt_y1[plasma_nn_wrapper_fixpt_l_2] = {plasma_nn_wrapper_fixpt_cast_5[plasma_nn_wrapper_fixpt_l_2][18:0], 1'b0};
    end

    y1_1_1 = plasma_nn_wrapper_fixpt_y1[0];
    y1_2_1 = plasma_nn_wrapper_fixpt_y1[1];
  end



  assign y1_1 = y1_1_1;

  assign y1_2 = y1_2_1;

endmodule  // plasma_nn_wrapper_fixpt

