// -------------------------------------------------------------
// 
// File Name: /home/kimberlychan/Desktop/DNN_Generality/matlab/codegen0_H8_L2_wL18_LoopNone/codegen/plasma_nn_wrapper/hdlsrc/plasma_nn_wrapper_fixpt.v
// Created: 2022-07-22 12:44:37
// 
// Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: plasma_nn_wrapper_fixpt
// Source Path: plasma_nn_wrapper_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module plasma_nn_wrapper_fixpt
          (x1_1,
           x1_2,
           x1_3,
           y1_1,
           y1_2);


  input   signed [17:0] x1_1;  // sfix18_En16
  input   signed [17:0] x1_2;  // sfix18_En16
  input   signed [2:0] x1_3;  // sfix3
  output  signed [17:0] y1_1;  // sfix18_En16
  output  signed [17:0] y1_2;  // sfix18_En16


  reg signed [17:0] y1_1_1;  // sfix18_En16
  reg signed [17:0] y1_2_1;  // sfix18_En16
  reg signed [17:0] plasma_nn_wrapper_fixpt_x1 [0:2];  // sfix18_En16 [3]
  reg signed [18:0] plasma_nn_wrapper_fixpt_c [0:2];  // sfix19_En16 [3]
  reg signed [17:0] plasma_nn_wrapper_fixpt_y [0:2];  // sfix18_En16 [3]
  reg signed [18:0] plasma_nn_wrapper_fixpt_c_0 [0:2];  // sfix19_En16 [3]
  reg signed [17:0] plasma_nn_wrapper_fixpt_y_0 [0:2];  // sfix18_En16 [3]
  reg signed [18:0] plasma_nn_wrapper_fixpt_c_1 [0:2];  // sfix19_En16 [3]
  reg signed [17:0] plasma_nn_wrapper_fixpt_xp1 [0:2];  // sfix18_En16 [3]
  reg signed [37:0] plasma_nn_wrapper_fixpt_c_2 [0:7];  // sfix38_En32 [8]
  reg signed [38:0] plasma_nn_wrapper_fixpt_c_3 [0:7];  // sfix39_En32 [8]
  reg signed [38:0] plasma_nn_wrapper_fixpt_maxval [0:7];  // sfix39_En32 [8]
  reg [17:0] plasma_nn_wrapper_fixpt_a1 [0:7];  // ufix18_En17 [8]
  reg signed [38:0] plasma_nn_wrapper_fixpt_c_4 [0:7];  // sfix39_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_c_5 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_maxval_0 [0:7];  // sfix40_En33 [8]
  reg [17:0] plasma_nn_wrapper_fixpt_a2 [0:7];  // ufix18_En17 [8]
  reg signed [38:0] plasma_nn_wrapper_fixpt_c_6 [0:1];  // sfix39_En33 [2]
  reg signed [17:0] plasma_nn_wrapper_fixpt_a3 [0:1];  // sfix18_En18 [2]
  reg signed [20:0] plasma_nn_wrapper_fixpt_c_7 [0:1];  // sfix21_En18 [2]
  reg signed [17:0] plasma_nn_wrapper_fixpt_a [0:1];  // sfix18_En16 [2]
  reg signed [17:0] plasma_nn_wrapper_fixpt_x [0:1];  // sfix18_En16 [2]
  reg signed [18:0] plasma_nn_wrapper_fixpt_c_8 [0:1];  // sfix19_En16 [2]
  reg signed [17:0] plasma_nn_wrapper_fixpt_y1 [0:1];  // sfix18_En18 [2]
  reg signed [31:0] plasma_nn_wrapper_fixpt_k;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_0;  // int32
  reg signed [38:0] plasma_nn_wrapper_fixpt_tmp;  // sfix39_En32
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_1;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l;  // int32
  reg signed [39:0] plasma_nn_wrapper_fixpt_tmp_0;  // sfix40_En33
  reg signed [31:0] plasma_nn_wrapper_fixpt_k_2;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_0;  // int32
  reg signed [31:0] plasma_nn_wrapper_fixpt_l_1;  // int32
  reg signed [17:0] plasma_nn_wrapper_fixpt_a0 [0:23];  // sfix18_En16 [24]
  reg signed [17:0] plasma_nn_wrapper_fixpt_a0_0 [0:63];  // sfix18_En16 [64]
  reg signed [17:0] plasma_nn_wrapper_fixpt_a0_1 [0:15];  // sfix18_En16 [16]
  reg signed [38:0] plasma_nn_wrapper_fixpt_t_0 [0:7];  // sfix39_En32 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_t_1 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_t_2 [0:1];  // sfix40_En33 [2]
  reg signed [18:0] plasma_nn_wrapper_fixpt_sub_cast [0:2];  // sfix19_En16 [3]
  reg signed [18:0] plasma_nn_wrapper_fixpt_add_cast [0:2];  // sfix19_En16 [3]
  reg signed [38:0] plasma_nn_wrapper_fixpt_add_cast_0 [0:7];  // sfix39_En32 [8]
  reg signed [38:0] plasma_nn_wrapper_fixpt_add_cast_1 [0:2];  // sfix39_En32 [3]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_2 [0:2];  // sfix64 [3]
  reg signed [35:0] plasma_nn_wrapper_fixpt_mul_temp [0:2];  // sfix36_En32 [3]
  reg signed [38:0] plasma_nn_wrapper_fixpt_add_cast_3 [0:2];  // sfix39_En32 [3]
  reg signed [38:0] plasma_nn_wrapper_fixpt_add_temp [0:2];  // sfix39_En32 [3]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_4 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_5 [0:7];  // sfix40_En33 [8]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_6 [0:7];  // sfix64 [8]
  reg signed [18:0] plasma_nn_wrapper_fixpt_cast [0:7];  // sfix19_En17 [8]
  reg signed [36:0] plasma_nn_wrapper_fixpt_mul_temp_0 [0:7];  // sfix37_En33 [8]
  reg signed [35:0] plasma_nn_wrapper_fixpt_add_cast_7 [0:7];  // sfix36_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_8 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_temp_0 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_9 [0:1];  // sfix40_En33 [2]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_temp_1 [0:1];  // sfix40_En33 [2]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_10 [0:7];  // sfix40_En33 [8]
  reg signed [63:0] plasma_nn_wrapper_fixpt_add_cast_11 [0:7];  // sfix64 [8]
  reg signed [18:0] plasma_nn_wrapper_fixpt_cast_0 [0:7];  // sfix19_En17 [8]
  reg signed [36:0] plasma_nn_wrapper_fixpt_mul_temp_1 [0:7];  // sfix37_En33 [8]
  reg signed [35:0] plasma_nn_wrapper_fixpt_add_cast_12 [0:7];  // sfix36_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_cast_13 [0:7];  // sfix40_En33 [8]
  reg signed [39:0] plasma_nn_wrapper_fixpt_add_temp_2 [0:7];  // sfix40_En33 [8]
  reg signed [20:0] plasma_nn_wrapper_fixpt_sub_cast_0 [0:1];  // sfix21_En18 [2]
  reg signed [18:0] plasma_nn_wrapper_fixpt_add_cast_14 [0:1];  // sfix19_En16 [2]
  reg signed [17:0] plasma_nn_wrapper_fixpt_cast_1 [0:1];  // sfix18_En16 [2]


  always @(x1_1, x1_2, x1_3) begin
    plasma_nn_wrapper_fixpt_a0[0] = 18'sb001110010111110111;
    plasma_nn_wrapper_fixpt_a0[1] = 18'sb001011101010001110;
    plasma_nn_wrapper_fixpt_a0[2] = 18'sb000001010110000110;
    plasma_nn_wrapper_fixpt_a0[3] = 18'sb110100011011111001;
    plasma_nn_wrapper_fixpt_a0[4] = 18'sb111010100111100010;
    plasma_nn_wrapper_fixpt_a0[5] = 18'sb110111011000010101;
    plasma_nn_wrapper_fixpt_a0[6] = 18'sb001001011000111010;
    plasma_nn_wrapper_fixpt_a0[7] = 18'sb111000001000110001;
    plasma_nn_wrapper_fixpt_a0[8] = 18'sb001001100110010001;
    plasma_nn_wrapper_fixpt_a0[9] = 18'sb111001101010110101;
    plasma_nn_wrapper_fixpt_a0[10] = 18'sb001110111110001001;
    plasma_nn_wrapper_fixpt_a0[11] = 18'sb111011001100110001;
    plasma_nn_wrapper_fixpt_a0[12] = 18'sb110101010011110000;
    plasma_nn_wrapper_fixpt_a0[13] = 18'sb110101110001011001;
    plasma_nn_wrapper_fixpt_a0[14] = 18'sb000111101001001110;
    plasma_nn_wrapper_fixpt_a0[15] = 18'sb111111001001010010;
    plasma_nn_wrapper_fixpt_a0[16] = 18'sb111111110011000000;
    plasma_nn_wrapper_fixpt_a0[17] = 18'sb001101011110011011;
    plasma_nn_wrapper_fixpt_a0[18] = 18'sb000100010001011000;
    plasma_nn_wrapper_fixpt_a0[19] = 18'sb000001100101110101;
    plasma_nn_wrapper_fixpt_a0[20] = 18'sb001101011100111110;
    plasma_nn_wrapper_fixpt_a0[21] = 18'sb110110001001100100;
    plasma_nn_wrapper_fixpt_a0[22] = 18'sb001011000101111100;
    plasma_nn_wrapper_fixpt_a0[23] = 18'sb001000000111101000;
    plasma_nn_wrapper_fixpt_a0_0[0] = 18'sb000100011101000101;
    plasma_nn_wrapper_fixpt_a0_0[1] = 18'sb111111000001010111;
    plasma_nn_wrapper_fixpt_a0_0[2] = 18'sb110000011000011000;
    plasma_nn_wrapper_fixpt_a0_0[3] = 18'sb111010110010011011;
    plasma_nn_wrapper_fixpt_a0_0[4] = 18'sb110101001100001001;
    plasma_nn_wrapper_fixpt_a0_0[5] = 18'sb001001011010101100;
    plasma_nn_wrapper_fixpt_a0_0[6] = 18'sb111001000011001111;
    plasma_nn_wrapper_fixpt_a0_0[7] = 18'sb111010010001111001;
    plasma_nn_wrapper_fixpt_a0_0[8] = 18'sb110111011101110101;
    plasma_nn_wrapper_fixpt_a0_0[9] = 18'sb000011010000110110;
    plasma_nn_wrapper_fixpt_a0_0[10] = 18'sb111000011010100100;
    plasma_nn_wrapper_fixpt_a0_0[11] = 18'sb000100111011100011;
    plasma_nn_wrapper_fixpt_a0_0[12] = 18'sb000110000011100000;
    plasma_nn_wrapper_fixpt_a0_0[13] = 18'sb000111111100001101;
    plasma_nn_wrapper_fixpt_a0_0[14] = 18'sb000100001100001000;
    plasma_nn_wrapper_fixpt_a0_0[15] = 18'sb110010101011101010;
    plasma_nn_wrapper_fixpt_a0_0[16] = 18'sb110111011101001110;
    plasma_nn_wrapper_fixpt_a0_0[17] = 18'sb001101001110100000;
    plasma_nn_wrapper_fixpt_a0_0[18] = 18'sb110100111000000100;
    plasma_nn_wrapper_fixpt_a0_0[19] = 18'sb001010011011010001;
    plasma_nn_wrapper_fixpt_a0_0[20] = 18'sb000001001110100001;
    plasma_nn_wrapper_fixpt_a0_0[21] = 18'sb001111111000000101;
    plasma_nn_wrapper_fixpt_a0_0[22] = 18'sb110001111101011001;
    plasma_nn_wrapper_fixpt_a0_0[23] = 18'sb111110001010100110;
    plasma_nn_wrapper_fixpt_a0_0[24] = 18'sb110011011010011011;
    plasma_nn_wrapper_fixpt_a0_0[25] = 18'sb001110110001111101;
    plasma_nn_wrapper_fixpt_a0_0[26] = 18'sb110000001001011111;
    plasma_nn_wrapper_fixpt_a0_0[27] = 18'sb001000110011000001;
    plasma_nn_wrapper_fixpt_a0_0[28] = 18'sb001010001001110101;
    plasma_nn_wrapper_fixpt_a0_0[29] = 18'sb001011110011000101;
    plasma_nn_wrapper_fixpt_a0_0[30] = 18'sb110010101100111011;
    plasma_nn_wrapper_fixpt_a0_0[31] = 18'sb111100110010110000;
    plasma_nn_wrapper_fixpt_a0_0[32] = 18'sb111001001111101111;
    plasma_nn_wrapper_fixpt_a0_0[33] = 18'sb001000011011101001;
    plasma_nn_wrapper_fixpt_a0_0[34] = 18'sb111101110011100010;
    plasma_nn_wrapper_fixpt_a0_0[35] = 18'sb001101001001000000;
    plasma_nn_wrapper_fixpt_a0_0[36] = 18'sb110110001011011010;
    plasma_nn_wrapper_fixpt_a0_0[37] = 18'sb111000011100010001;
    plasma_nn_wrapper_fixpt_a0_0[38] = 18'sb110101001000010100;
    plasma_nn_wrapper_fixpt_a0_0[39] = 18'sb110110000100101001;
    plasma_nn_wrapper_fixpt_a0_0[40] = 18'sb001001100110101101;
    plasma_nn_wrapper_fixpt_a0_0[41] = 18'sb000110011011110101;
    plasma_nn_wrapper_fixpt_a0_0[42] = 18'sb000001100110000111;
    plasma_nn_wrapper_fixpt_a0_0[43] = 18'sb110100101000110111;
    plasma_nn_wrapper_fixpt_a0_0[44] = 18'sb001110111100010000;
    plasma_nn_wrapper_fixpt_a0_0[45] = 18'sb000011111001111110;
    plasma_nn_wrapper_fixpt_a0_0[46] = 18'sb111001101110111010;
    plasma_nn_wrapper_fixpt_a0_0[47] = 18'sb111111100111010100;
    plasma_nn_wrapper_fixpt_a0_0[48] = 18'sb111101000101011001;
    plasma_nn_wrapper_fixpt_a0_0[49] = 18'sb110010011011100101;
    plasma_nn_wrapper_fixpt_a0_0[50] = 18'sb110111101011010110;
    plasma_nn_wrapper_fixpt_a0_0[51] = 18'sb110011111100100011;
    plasma_nn_wrapper_fixpt_a0_0[52] = 18'sb110101111010101111;
    plasma_nn_wrapper_fixpt_a0_0[53] = 18'sb110111101011011011;
    plasma_nn_wrapper_fixpt_a0_0[54] = 18'sb111110010110010000;
    plasma_nn_wrapper_fixpt_a0_0[55] = 18'sb110000100011111110;
    plasma_nn_wrapper_fixpt_a0_0[56] = 18'sb001100111000110000;
    plasma_nn_wrapper_fixpt_a0_0[57] = 18'sb001110001110111011;
    plasma_nn_wrapper_fixpt_a0_0[58] = 18'sb111111101101010010;
    plasma_nn_wrapper_fixpt_a0_0[59] = 18'sb111111101001111111;
    plasma_nn_wrapper_fixpt_a0_0[60] = 18'sb111010110011101001;
    plasma_nn_wrapper_fixpt_a0_0[61] = 18'sb001100110011010011;
    plasma_nn_wrapper_fixpt_a0_0[62] = 18'sb111011110100001101;
    plasma_nn_wrapper_fixpt_a0_0[63] = 18'sb110011100011101111;
    plasma_nn_wrapper_fixpt_a0_1[0] = 18'sb000110000100000110;
    plasma_nn_wrapper_fixpt_a0_1[1] = 18'sb111001001010100000;
    plasma_nn_wrapper_fixpt_a0_1[2] = 18'sb111000011101000100;
    plasma_nn_wrapper_fixpt_a0_1[3] = 18'sb111011001011011100;
    plasma_nn_wrapper_fixpt_a0_1[4] = 18'sb001010010001110011;
    plasma_nn_wrapper_fixpt_a0_1[5] = 18'sb110000011111100010;
    plasma_nn_wrapper_fixpt_a0_1[6] = 18'sb110001011000000111;
    plasma_nn_wrapper_fixpt_a0_1[7] = 18'sb110101011010000101;
    plasma_nn_wrapper_fixpt_a0_1[8] = 18'sb111111110110011111;
    plasma_nn_wrapper_fixpt_a0_1[9] = 18'sb001001100011101100;
    plasma_nn_wrapper_fixpt_a0_1[10] = 18'sb000100101110100101;
    plasma_nn_wrapper_fixpt_a0_1[11] = 18'sb111110011011011111;
    plasma_nn_wrapper_fixpt_a0_1[12] = 18'sb000110110101001011;
    plasma_nn_wrapper_fixpt_a0_1[13] = 18'sb111101011111100010;
    plasma_nn_wrapper_fixpt_a0_1[14] = 18'sb001110011111111100;
    plasma_nn_wrapper_fixpt_a0_1[15] = 18'sb111001000011011110;
    plasma_nn_wrapper_fixpt_t_0[0] = 39'sh7F70A38000;
    plasma_nn_wrapper_fixpt_t_0[1] = 39'sh0034D48000;
    plasma_nn_wrapper_fixpt_t_0[2] = 39'sh7F38408000;
    plasma_nn_wrapper_fixpt_t_0[3] = 39'sh7F1B9F0000;
    plasma_nn_wrapper_fixpt_t_0[4] = 39'sh000E200000;
    plasma_nn_wrapper_fixpt_t_0[5] = 39'sh007D6E0000;
    plasma_nn_wrapper_fixpt_t_0[6] = 39'sh00E6AA0000;
    plasma_nn_wrapper_fixpt_t_0[7] = 39'sh7F42830000;
    plasma_nn_wrapper_fixpt_t_1[0] = 40'sh00AD560000;
    plasma_nn_wrapper_fixpt_t_1[1] = 40'shFFF5E60000;
    plasma_nn_wrapper_fixpt_t_1[2] = 40'shFEF77C0000;
    plasma_nn_wrapper_fixpt_t_1[3] = 40'shFF9D9A0000;
    plasma_nn_wrapper_fixpt_t_1[4] = 40'shFEC8EA0000;
    plasma_nn_wrapper_fixpt_t_1[5] = 40'shFE87240000;
    plasma_nn_wrapper_fixpt_t_1[6] = 40'sh018F9E0000;
    plasma_nn_wrapper_fixpt_t_1[7] = 40'sh0216440000;
    plasma_nn_wrapper_fixpt_t_2[0] = 40'shFE40A80000;
    plasma_nn_wrapper_fixpt_t_2[1] = 40'sh0127070000;
    plasma_nn_wrapper_fixpt_tmp = 39'sh0000000000;
    plasma_nn_wrapper_fixpt_tmp_0 = 40'sh0000000000;
    //HDL code generation from MATLAB function: plasma_nn_wrapper_fixpt
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    //                                                                          %
    //          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
    //                                                                          %
    //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    plasma_nn_wrapper_fixpt_x1[0] = x1_1;
    plasma_nn_wrapper_fixpt_x1[1] = x1_2;
    plasma_nn_wrapper_fixpt_x1[2] = {x1_3[1:0], 16'b0000000000000000};
    //PLASMA_NN neural network simulation function.
    //
    // Auto-generated by MATLAB, 22-Jul-2022 12:43:56.
    // 
    // [y1] = plasma_nn(x1) takes these arguments:
    //   x = 3xQ matrix, input #1
    // and returns:
    //   y = 2xQ matrix, output #1
    // where Q is the number of samples.
    // ===== NEURAL NETWORK CONSTANTS =====
    // Input 1
    // Layer 1
    // Layer 2
    // Layer 3
    // Output 1
    // ===== SIMULATION ========
    // Dimensions
    // samples
    // Input 1
    // ===== MODULE FUNCTIONS ========
    // Map Minimum and Maximum Input Processing Function

    for(plasma_nn_wrapper_fixpt_k = 32'sd0; plasma_nn_wrapper_fixpt_k <= 32'sd2; plasma_nn_wrapper_fixpt_k = plasma_nn_wrapper_fixpt_k + 32'sd1) begin
      plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k][17], plasma_nn_wrapper_fixpt_x1[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_sub_cast[plasma_nn_wrapper_fixpt_k] - 19'sb1110000000000000000;
      plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c[plasma_nn_wrapper_fixpt_k][17:0];
      plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k][17], plasma_nn_wrapper_fixpt_y[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_0[plasma_nn_wrapper_fixpt_k][17:0];
      plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] = {plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k][17], plasma_nn_wrapper_fixpt_y_0[plasma_nn_wrapper_fixpt_k]};
      plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_add_cast[plasma_nn_wrapper_fixpt_k] + 19'sb1110000000000000000;
      plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k] = plasma_nn_wrapper_fixpt_c_1[plasma_nn_wrapper_fixpt_k][17:0];
    end

    // Layer 1
    // Linear Positive Transfer Function
    // Layer 2

    for(plasma_nn_wrapper_fixpt_l_0 = 32'sd0; plasma_nn_wrapper_fixpt_l_0 <= 32'sd7; plasma_nn_wrapper_fixpt_l_0 = plasma_nn_wrapper_fixpt_l_0 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0] = 38'sh0000000000;

      for(plasma_nn_wrapper_fixpt_k_0 = 32'sd0; plasma_nn_wrapper_fixpt_k_0 <= 32'sd2; plasma_nn_wrapper_fixpt_k_0 = plasma_nn_wrapper_fixpt_k_0 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0][37], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0]};
        plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0] = {{29{plasma_nn_wrapper_fixpt_k_0[31]}}, {plasma_nn_wrapper_fixpt_k_0, 3'b000}};
        plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_a0[plasma_nn_wrapper_fixpt_l_0 + plasma_nn_wrapper_fixpt_add_cast_2[plasma_nn_wrapper_fixpt_k_0]] * plasma_nn_wrapper_fixpt_xp1[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_k_0] = {{3{plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0][35]}}, plasma_nn_wrapper_fixpt_mul_temp[plasma_nn_wrapper_fixpt_k_0]};
        plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0] = plasma_nn_wrapper_fixpt_add_cast_1[plasma_nn_wrapper_fixpt_k_0] + plasma_nn_wrapper_fixpt_add_cast_3[plasma_nn_wrapper_fixpt_k_0];
        plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_temp[plasma_nn_wrapper_fixpt_k_0][37:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l_0] = {plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0][37], plasma_nn_wrapper_fixpt_c_2[plasma_nn_wrapper_fixpt_l_0]};
      plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_add_cast_0[plasma_nn_wrapper_fixpt_l_0] + plasma_nn_wrapper_fixpt_t_0[plasma_nn_wrapper_fixpt_l_0];
      if (39'sh0000000000 < plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0]) begin
        plasma_nn_wrapper_fixpt_tmp = plasma_nn_wrapper_fixpt_c_3[plasma_nn_wrapper_fixpt_l_0];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp = 39'sh0000000000;
      end
      plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_tmp;
      plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_l_0] = plasma_nn_wrapper_fixpt_maxval[plasma_nn_wrapper_fixpt_l_0][32:15];
      plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l_0] = 39'sh0000000000;
    end

    // Linear Positive Transfer Function

    for(plasma_nn_wrapper_fixpt_l = 32'sd0; plasma_nn_wrapper_fixpt_l <= 32'sd7; plasma_nn_wrapper_fixpt_l = plasma_nn_wrapper_fixpt_l + 32'sd1) begin

      for(plasma_nn_wrapper_fixpt_k_1 = 32'sd0; plasma_nn_wrapper_fixpt_k_1 <= 32'sd7; plasma_nn_wrapper_fixpt_k_1 = plasma_nn_wrapper_fixpt_k_1 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l][38], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l]};
        plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1] = {{29{plasma_nn_wrapper_fixpt_k_1[31]}}, {plasma_nn_wrapper_fixpt_k_1, 3'b000}};
        plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k_1] = {1'b0, plasma_nn_wrapper_fixpt_a1[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_a0_0[plasma_nn_wrapper_fixpt_l + plasma_nn_wrapper_fixpt_add_cast_6[plasma_nn_wrapper_fixpt_k_1]] * plasma_nn_wrapper_fixpt_cast[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_mul_temp_0[plasma_nn_wrapper_fixpt_k_1][35:0];
        plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_1] = {{4{plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1][35]}}, plasma_nn_wrapper_fixpt_add_cast_7[plasma_nn_wrapper_fixpt_k_1]};
        plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1] = plasma_nn_wrapper_fixpt_add_cast_5[plasma_nn_wrapper_fixpt_k_1] + plasma_nn_wrapper_fixpt_add_cast_8[plasma_nn_wrapper_fixpt_k_1];
        plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_temp_0[plasma_nn_wrapper_fixpt_k_1][38:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_l] = {plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l][38], plasma_nn_wrapper_fixpt_c_4[plasma_nn_wrapper_fixpt_l]};
      plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_add_cast_4[plasma_nn_wrapper_fixpt_l] + plasma_nn_wrapper_fixpt_t_1[plasma_nn_wrapper_fixpt_l];
      if (40'sh0000000000 < plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l]) begin
        plasma_nn_wrapper_fixpt_tmp_0 = plasma_nn_wrapper_fixpt_c_5[plasma_nn_wrapper_fixpt_l];
      end
      else begin
        plasma_nn_wrapper_fixpt_tmp_0 = 40'sh0000000000;
      end
      plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_tmp_0;
      plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_l] = plasma_nn_wrapper_fixpt_maxval_0[plasma_nn_wrapper_fixpt_l][33:16];
    end

    // Layer 3
    // Output 1
    // Map Minimum and Maximum Output Reverse-Processing Function

    for(plasma_nn_wrapper_fixpt_l_1 = 32'sd0; plasma_nn_wrapper_fixpt_l_1 <= 32'sd1; plasma_nn_wrapper_fixpt_l_1 = plasma_nn_wrapper_fixpt_l_1 + 32'sd1) begin
      plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = 39'sh0000000000;

      for(plasma_nn_wrapper_fixpt_k_2 = 32'sd0; plasma_nn_wrapper_fixpt_k_2 <= 32'sd7; plasma_nn_wrapper_fixpt_k_2 = plasma_nn_wrapper_fixpt_k_2 + 32'sd1) begin
        plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][38], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
        plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_k_2] = {{31{plasma_nn_wrapper_fixpt_k_2[31]}}, {plasma_nn_wrapper_fixpt_k_2, 1'b0}};
        plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_2] = {1'b0, plasma_nn_wrapper_fixpt_a2[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_a0_1[plasma_nn_wrapper_fixpt_l_1 + plasma_nn_wrapper_fixpt_add_cast_11[plasma_nn_wrapper_fixpt_k_2]] * plasma_nn_wrapper_fixpt_cast_0[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_mul_temp_1[plasma_nn_wrapper_fixpt_k_2][35:0];
        plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_2] = {{4{plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2][35]}}, plasma_nn_wrapper_fixpt_add_cast_12[plasma_nn_wrapper_fixpt_k_2]};
        plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_k_2] = plasma_nn_wrapper_fixpt_add_cast_10[plasma_nn_wrapper_fixpt_k_2] + plasma_nn_wrapper_fixpt_add_cast_13[plasma_nn_wrapper_fixpt_k_2];
        plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_temp_2[plasma_nn_wrapper_fixpt_k_2][38:0];
      end

      plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1][38], plasma_nn_wrapper_fixpt_c_6[plasma_nn_wrapper_fixpt_l_1]};
      plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_cast_9[plasma_nn_wrapper_fixpt_l_1] + plasma_nn_wrapper_fixpt_t_2[plasma_nn_wrapper_fixpt_l_1];
      plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_temp_1[plasma_nn_wrapper_fixpt_l_1][32:15];
      plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_1] = {{3{plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_l_1][17]}}, plasma_nn_wrapper_fixpt_a3[plasma_nn_wrapper_fixpt_l_1]};
      plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_sub_cast_0[plasma_nn_wrapper_fixpt_l_1] - 21'sb111000000000000000000;
      plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_c_7[plasma_nn_wrapper_fixpt_l_1][19:2];
      plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_a[plasma_nn_wrapper_fixpt_l_1];
      plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_1][17], plasma_nn_wrapper_fixpt_x[plasma_nn_wrapper_fixpt_l_1]};
      plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_add_cast_14[plasma_nn_wrapper_fixpt_l_1] + 19'sb1110000000000000000;
      plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l_1] = plasma_nn_wrapper_fixpt_c_8[plasma_nn_wrapper_fixpt_l_1][17:0];
      plasma_nn_wrapper_fixpt_y1[plasma_nn_wrapper_fixpt_l_1] = {plasma_nn_wrapper_fixpt_cast_1[plasma_nn_wrapper_fixpt_l_1][15:0], 2'b00};
    end

    y1_1_1 = {{2{plasma_nn_wrapper_fixpt_y1[0][17]}}, plasma_nn_wrapper_fixpt_y1[0][17:2]};
    y1_2_1 = {{2{plasma_nn_wrapper_fixpt_y1[1][17]}}, plasma_nn_wrapper_fixpt_y1[1][17:2]};
  end



  assign y1_1 = y1_1_1;

  assign y1_2 = y1_2_1;

endmodule  // plasma_nn_wrapper_fixpt

